### ISSUE TITLE
cmorization of REMO output

### ISSUE THREAD

**Issue by larsbuntemeyer** [remo-rcm/pyremo#10]
# Summary

For the new netcdf remo output, we should simplify the cmorization process, using typcically [xr.resample](https://xarray.pydata.org/en/v0.20.1/generated/xarray.DataArray.resample.html) functions. Right now, there are no real CORDEX cmor tables in any standard format. We can try to reformat the output as close as possible to cmor standards and incorporate the [python API](https://cmor.llnl.gov/mydoc_cmor3_python/) at another time.

## To Do

- [x] Create a mapping table that maps [remo codes](https://github.com/remo-rcm/tables/blob/master/code-list/code-list.csv) to cf standard names
- [ ] Create CORDEX mip tables (this should be a community effort)
- [x] Add `_bounds` variable in space and time (if not available)
- [x] Check for Cordex cmor tables in json format (not available yet, see https://github.com/PCMDI/cordex-cmor-tables/pull/1)

Maybe we can also use [cf-xarray](https://cf-xarray.readthedocs.io/en/latest/index.html) that should handle all cf related issues.

see also: https://github.com/euro-cordex/py-cordex/issues/26

**Comment by larsbuntemeyer** [comment]
@ludwiglierhammer

Maybe this could come in handy for handling bounds: https://cf-xarray.readthedocs.io/en/latest/generated/xarray.Dataset.cf.add_bounds.html

**Comment by larsbuntemeyer** [comment]
function that can be used to determine frequency of a time-axis: `xr.infer_freq`
works mostly for subdaily and daily frequencies, for monthly, it has to be first of month.

**Comment by larsbuntemeyer** [comment]
example for grid mapping: https://github.com/PCMDI/cmor/issues/82

**Comment by ludwiglierhammer** [comment]
in remo_cmor.py function _define_axes the time axis name is 'time'. This has to be more flexible because in the test CORDEX tables (CORDEX_coordinate.json) there are two time axis defined: time and time1. Time1 is used e.g. for 3hourly data (CORDEX_3hr.json).
The differnec between time and time1 is: 
time -> "must_have_bounds": "yes", 
time1 ->  "must_have_bounds": "no"

**Comment by larsbuntemeyer** [comment]
This effort has been moved to: https://github.com/euro-cordex/py-cordex/issues/26
